// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin from "./routes/admin.tsx";
import * as $api_admin_posts_approve from "./routes/api/admin/posts/approve.ts";
import * as $api_admin_posts_approved from "./routes/api/admin/posts/approved.ts";
import * as $api_admin_posts_moderate from "./routes/api/admin/posts/moderate.ts";
import * as $api_admin_posts_pending from "./routes/api/admin/posts/pending.ts";
import * as $api_admin_posts_rejected from "./routes/api/admin/posts/rejected.ts";
import * as $api_admin_stats from "./routes/api/admin/stats.ts";
import * as $api_auth_callback from "./routes/api/auth/callback.ts";
import * as $api_auth_github from "./routes/api/auth/github.ts";
import * as $api_auth_linuxdo from "./routes/api/auth/linuxdo.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_me from "./routes/api/auth/me.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_posts_collect from "./routes/api/posts/collect.ts";
import * as $api_posts_create from "./routes/api/posts/create.ts";
import * as $api_posts_index from "./routes/api/posts/index.ts";
import * as $create from "./routes/create.tsx";
import * as $dress from "./routes/dress.tsx";
import * as $index from "./routes/index.tsx";
import * as $profile from "./routes/profile.tsx";
import * as $status_401 from "./routes/status/401.tsx";
import * as $status_403 from "./routes/status/403.tsx";
import * as $status_500 from "./routes/status/500.tsx";
import * as $status_502 from "./routes/status/502.tsx";
import * as $status_503 from "./routes/status/503.tsx";
import * as $status_index from "./routes/status/index.tsx";
import * as $AdminPanel from "./islands/AdminPanel.tsx";
import * as $AuthMenu from "./islands/AuthMenu.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $CreateContentForm from "./islands/CreateContentForm.tsx";
import * as $HeaderNavigation from "./islands/HeaderNavigation.tsx";
import * as $LayoutManager from "./islands/LayoutManager.tsx";
import * as $NavigationState from "./islands/NavigationState.tsx";
import * as $PostForm from "./islands/PostForm.tsx";
import * as $PostGrid from "./islands/PostGrid.tsx";
import * as $SidebarNavigation from "./islands/SidebarNavigation.tsx";
import * as $StatusDropdown from "./islands/StatusDropdown.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin.tsx": $admin,
    "./routes/api/admin/posts/approve.ts": $api_admin_posts_approve,
    "./routes/api/admin/posts/approved.ts": $api_admin_posts_approved,
    "./routes/api/admin/posts/moderate.ts": $api_admin_posts_moderate,
    "./routes/api/admin/posts/pending.ts": $api_admin_posts_pending,
    "./routes/api/admin/posts/rejected.ts": $api_admin_posts_rejected,
    "./routes/api/admin/stats.ts": $api_admin_stats,
    "./routes/api/auth/callback.ts": $api_auth_callback,
    "./routes/api/auth/github.ts": $api_auth_github,
    "./routes/api/auth/linuxdo.ts": $api_auth_linuxdo,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/me.ts": $api_auth_me,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/posts/collect.ts": $api_posts_collect,
    "./routes/api/posts/create.ts": $api_posts_create,
    "./routes/api/posts/index.ts": $api_posts_index,
    "./routes/create.tsx": $create,
    "./routes/dress.tsx": $dress,
    "./routes/index.tsx": $index,
    "./routes/profile.tsx": $profile,
    "./routes/status/401.tsx": $status_401,
    "./routes/status/403.tsx": $status_403,
    "./routes/status/500.tsx": $status_500,
    "./routes/status/502.tsx": $status_502,
    "./routes/status/503.tsx": $status_503,
    "./routes/status/index.tsx": $status_index,
  },
  islands: {
    "./islands/AdminPanel.tsx": $AdminPanel,
    "./islands/AuthMenu.tsx": $AuthMenu,
    "./islands/Counter.tsx": $Counter,
    "./islands/CreateContentForm.tsx": $CreateContentForm,
    "./islands/HeaderNavigation.tsx": $HeaderNavigation,
    "./islands/LayoutManager.tsx": $LayoutManager,
    "./islands/NavigationState.tsx": $NavigationState,
    "./islands/PostForm.tsx": $PostForm,
    "./islands/PostGrid.tsx": $PostGrid,
    "./islands/SidebarNavigation.tsx": $SidebarNavigation,
    "./islands/StatusDropdown.tsx": $StatusDropdown,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
